server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
        - id: order-service
          uri: http://localhost:8082/
          predicates:
            - Path=/orders/**
        - id: notification-service
          uri: http://localhost:9092/
          predicates:
            - Path=/notification/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
